specVersion: 0.0.1
description: Crowdloan tracking on Kusama
repository: https://github.com/Moehringen/crowdloan
schema: ./schema.graphql
network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
  #endpoint: wss://kusama-rpc.polkadot.io/
  #dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: KusamaRuntime
    kind: substrate/Runtime
    filter: 
      specName: kusama
    startBlock: 7828000 
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          #filter:
          #  module: balances
          #  method: Deposit
          #- handler: handleCall
          #kind: substrate/CallHandler
